ALTER TABLE itineraries 
ADD COLUMN IF NOT EXISTS duration VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS tourist_spots TEXT NULL,
ADD COLUMN IF NOT EXISTS budget DECIMAL(10,2) NULL,
ADD COLUMN IF NOT EXISTS max_visitors INT NULL,
ADD COLUMN IF NOT EXISTS status ENUM('active', 'inactive') NOT NULL DEFAULT 'active';
